# Site settings
title: Row Hard No Excuses
email: jamiefolsom@gmail.com
description: ""
baseurl: ""
url: "http://lanternfilms.github.io/rowhard"

# Build settings
markdown: kramdown
permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: "http://lanternfilms.github.io/rowhard"
  relativeLinks: 'http://lanternfilms.github.io/rowhard/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Genre"
          options:
            - name: "Trailer"
              value: "trailer"
            - name: "About"
              value: "about"
            - name: "Press"
              value: "press"
            - name: "Screenings"
              value: "screenings"
            - name: "Contact"
              value: "contact"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: ""
